Update README.md
PrusaMK2Users/3030_Haribo_Edition pull request #37
Opened 2017-05-31 21:23 UTC by mihec87

Merged line 16 and 18 so information about screw length is in one line instead of interrupted with line 17(the firmware changes).

2017-05-31 21:23 UTC, ryanneufeld requested changes

2017-05-31 21:23 UTC, ryanneufeld commented on Instructions/README.md
> +- make sure you use the correct length M6 screws, most pieces use M6 x 12 but others use M6 x 14, M6x12mm screws should be used for the parts that have recessed holes.  Namely: Y idler and motor hold
Maybe one line per bolt size explaining where they would be used would be more clear?

2017-06-01 08:51 UTC, mihec87 commented
Ok made changes like you suggested-it is even better now..
https://github.com/PrusaMK2Users/3030_Haribo_Edition/pull/37/commits/9d02bf3b8f8213040062c415652aa884a316972f

2017-06-01 17:21 UTC, ryanneufeld approved these changes

2017-06-01 17:21 UTC, merged

2017-06-01 17:21 UTC, ryanneufeld commented
Thanks for contributing!